### ISSUE TITLE
Enhancement: Percentage setting for maxHeight based on surrounding div container

### ISSUE THREAD

**Issue by kschwidder** [angular-gantt/angular-gantt#324]
It would be nice if maxHeight could be adjusted according to its surrounded div tag via a percentage setting.
Could it be possible to call a function for maxHeight which does this ?

**Comment by Toilal** [comment]
I'm not sure I really understand this question. Could you make a small sketch to visualize what layout you want to achieve ? Won't it be possible with pure CSS by adding a extra div container ?

**Comment by Schweigi** [comment]
I`m not sure if I understand the question correct but I think this would need to be done with JS since a pure CSS solution may be difficult as certain parts use absolute positioning.

One way would be to have a function which gets the height of another element and then adjusts the maxHeight accordingly. Additonally an `onresize` event handler can be registered on the `window` to recalculate the height in case the browser windows changes in size.

Sample code which could be an own directive:
```
var calculateHeight = function() {
    scope.maxHeight = otherElement1.offsetHeight - otherElement2.offsetHeight;
};

angular.element($window).bind('resize', function() {
    scope.$apply(function() {
        calculateHeight();
    });
});

calculateHeight();
```

**Comment by kschwidder** [comment]
will test the mentioned solution. This is exactly what I was looking for. I.e. if the surrounding div has a height in % and the browser is resized than maxHeight would be adjusted too.
