### ISSUE TITLE
Set label color

### ISSUE THREAD

**Issue by kschwidder** [angular-gantt/angular-gantt#351]
Is it possible to set a color for the label of the row ? Currently only task labels are supported.
It would be nice to to do so instead of customizing the templates.

**Comment by Toilal** [comment]
You can use a CSS class in a `Row` model, and then style the row as you want.

Even if color property seems handy, I'm not sure we should support them, because CSS styling is really more powerful and wide.

I'll vote to just deprecate "color" property support from `Task` and `Row` model. What's your opinion @Schweigi ?

**Comment by kschwidder** [comment]
Sorry Toilal. I meant to set the color of the label section (e.g. coloring a tree label). Is this also possible via CSS ?

**Comment by Toilal** [comment]
Yes, you can setup one or many class names on `Row` model using `classes` property, and then this class will appear in the DOM on each DOM element representing this `Row` (label included). 

The class will be applied on multiple DOM elements used to display the row (the background, the foreground, ...), so you may need to add more classes to select only the label, but it should be possible.

No problem @kschwidder, asking questions is just fine :)
