### ISSUE TITLE
Task disappeared after moved out from time range and scale changed .

### ISSUE THREAD

**Issue by ronihcohen** [angular-gantt/angular-gantt#369]
1. Time range was from NOW to +1 month.
2. Scale was set to months so the previous month is visible even if it's out of range.
2. Added a task to previous month.
3. Changed scale from month to week and then from week back to months.
4. The Task isn't visible in the Gantt any more.

**Comment by Toilal** [comment]
I think I can reproduce and understand why the bug occurs.

For example, when setting from `from-date` at the end of a particular month, the whole column for this month is rendered, but tasks are filtered out based on the `from-date` value.

Filtering of task should be based on begining date of the first column and end date of the last column, instead of using raw `from-date` and `to-date`.

What's strange to me is that when I read the [code of the task filtering](https://github.com/angular-gantt/angular-gantt/blob/master/src/core/ui/limit/taskLimit.filter.js#L15-L21), it seems to be actual implementation, so the bug may be hard to fix ...

**Comment by Toilal** [comment]
When, my reading was bad, date from columns are used only when from-date and to-date are undefined. So i'll change this to always use date from columns for filtering tasks.
