### ISSUE TITLE
DrawTask typo?

### ISSUE THREAD

**Issue by robfarmer-ai** [angular-gantt/angular-gantt#404]
I believe the code below should be `document.on` not `document.one`

```javascript
document.one('mouseup', function() {
     element.off('mousemove', moveTrigger);
});
```

in angular-gantt/assets/angular-gantt-drawtask-plugin.js

**Comment by Schweigi** [comment]
The code is correct because it is inside the function `var deferDrawing = function(startX){...}` which is executed on each `mousedown` call.

So on each `mousedown` call we register the `mousemove` event and when the `mouseup` event gets triggered we would like to unsubscribe from the `mousemove` event again. At the same time the `mouseup` event should also be unsubscribed and thats why we use `one`.
```
element.on('mousemove', moveTrigger);
document.one('mouseup', function() {
    element.off('mousemove', moveTrigger);
});
```
