### ISSUE TITLE
[TOOLTIP] [BUG] Double tooltip when template-url/content are defined

### ISSUE THREAD

**Issue by v4l3r10** [angular-gantt/angular-gantt#415]
![tooltipdoubling](https://cloud.githubusercontent.com/assets/3998542/7302100/45203972-e9e7-11e4-9665-9617ccd529ca.png)

```html
	<div gantt="" data="data" timespans="timespans" 
		show-side="options.labelsEnabled" 
		daily="options.daily" 
		filter-task="{'name': options.filterTask}"
		filter-row="{'name': options.filterRow}" 
		sort-mode="options.sortMode" 
		view-scale="options.scale" 
		column-width="getColumnWidth(options.width, options.scale, options.zoom)" 
		auto-expand="options.autoExpand" 
		task-out-of-range="options.taskOutOfRange" 
		from-date="options.fromDate" 
		to-date="options.toDate" 
		allow-side-resizing="options.allowSideResizing" 
		task-content="options.taskContentEnabled ? options.taskContent : undefined" 
		row-content="options.rowContentEnabled ? options.rowContent : undefined"
		current-date="options.currentDate" 
		current-date-value="options.currentDateValue" 
		headers="options.width &amp;&amp; options.shortHeaders || options.longHeaders" 
		max-height="options.maxHeight &amp;&amp; 300 || 0" 
		time-frames="options.timeFrames" 
		date-frames="options.dateFrames" 
		time-frames-non-working-mode="options.timeFramesNonWorkingMode" 
		time-frames-magnet="options.timeFramesMagnet" 
		api="options.api" 
		column-magnet="options.columnMagnet">
		<gantt-table columns="['model.name']"></gantt-table>
		<gantt-tooltips template-url="js/angular/template/associazione-tooltip-task.tmpl.html" ><gantt-tooltips/>
	</div>
```

templatefile
```
<div ng-cloak
		 class="gantt-task-info"
		 ng-show="displayed"
		 ng-class="isRightAligned ? 'gantt-task-infoArrowR' : 'gantt-task-infoArrow'"
		 ng-style="{top: taskRect.top + 'px', marginTop: -elementHeight - 8 + 'px'}">
		<div class="gantt-task-info-content">
				{{ task.model.name }}</br>
				<small>{{ task.isMilestone === true && (task.getFromLabel()) || (task.getFromLabel() + ' - ' + task.getToLabel());}}</small>
				<small>{{ 'Durata:'+ task.model.data.durata }}</small></br>
				<small>{{ 'Evento ID:'+ task.model.data.evento_id }}</small>
				</br>
				<small>{{ 'Intervento ID:'+ task.model.data.intervento_id }}</small>
				</br>     
				<small>{{ 'Tipo Intervento ID:'+ task.model.data.tipo_intervento_id }}</small>
				</br>
				<small>{{ 'Note:'+ task.model.data.note }}</small>
		</div>
</div>

```

someone has this problem?

**Comment by crl73** [comment]
We have the same probleme.

**Comment by v4l3r10** [comment]
+1

**Comment by julienmeyer** [comment]
+1

**Comment by v4l3r10** [comment]
can you  paste your config Julien?

**Comment by julienmeyer** [comment]
I use angular-gantt v1.2.5

The gantt chart definition
```
<div class="row">
        <div class="col-md-12">
            <div gantt
                 data="ganttData"
                 api="registerApi"
                 filter-row="filterFunction"
                 view-scale = "viewScale"
                 from-date="fromDate"
                 to-date="toDate"
                 column-magnet = "columnMagnet"
                 show-side="true"
                 time-frames-working-mode="visible"
                 time-frames-non-working-mode="visible">
                <gantt-table></gantt-table>
                <gantt-tooltips
                    template-url="planning/planning/planning-gantt/planning-gantt-task-tooltip.tmpl.html">


                </gantt-tooltips>
                <gantt-movable enabled="true"
                               allow-moving="true"
                               allow-resizing="true"
                               allow-row-switching="true">
            </div>
</div>
```
And the template file : 
```
<div ng-cloak
     class="gantt-task-info"
     ng-show="displayed"
     ng-class="isRightAligned ? 'gantt-task-infoArrowR' : 'gantt-task-infoArrow'"
     ng-style="{top: taskRect.top + 'px', marginTop: -elementHeight - 8 + 'px'}">
    <div class="gantt-task-info-content">
        <b><u>{{ task.model.name }}</u></b></br>
        <small>
            {{ task.model.data.description}} <br><br>
            {{ task.model.from | amDateFormat:'D/M/YY HH:mm' }} ${_("to")} {{ task.model.to | amDateFormat:'HH:mm' }}<br>
            {{ task.model.data.customer.nameA}} {{ task.model.data.customer.nameB}}<br>
            <span ng-if="task.model.data.customer.phone">{{ task.model.data.customer.phone}}<br></span>
            <span ng-if="task.model.data.customer.mobilePhone">{{ task.model.data.customer.mobilePhone}}<br></span>
            {{ task.model.data.locationComplete }}
        </small>
    </div>
</div>
```

**Comment by Schweigi** [comment]
I tried to reproduce this bug with the demo but it is working correctly all the time. I tried with a `url`, `content` and even by specifying both. I also use the `content` property for my own project and never had a problem with it.

Please make sure you have the newest version (maybe try with the master branch version) and also make sure that the tooltip plugin is loaded once only. It would be good if you guys could post all the JS files you include.

**Comment by TinOo512** [comment]
Hi, I've got the same problem here :) I tried many things and I found a fix which is probably really bad but it works.

It seems to appear only when we specify the `max-height` attribute and only on OS where the function `getScrollBarWidth` returns 0 (on Yosemite for example). It also depends on the `length` of the row labels. The thing which is really weird is that I couldn't reproduce it with the exact same data on a Plunker, ... 

Except if I specify a bad `side-width` as you can see here : [bug on plunker](http://plnkr.co/edit/tRyB1tFsN0hSkldUm104?p=preview)

But on my app I didn't need to specify the `side-width`, the one which is calculated is wrong so the bug appears without this attribute. By the way when I manually set `side-width` it seems to be overwritten by the dynamic value.

To fix it I return 1 instead of 0 in `getScrollBarWidth` like this : `return (w1 - w2 || 1);`

This fixes the bug at the initialization of the gantt but it appears again when you drag the sidebar, to fix this one I add `gantt-wrapper * { box-sizing: border-box; }`

I think the calculated width of the sidebar is missing a few pixels, I don't know from where, ... I hope this will help you find a prettier fix than this one :)

**Comment by TinOo512** [comment]
@v4l3r10 @Schweigi 
I had the same issue and I figured out that it was an HTML markup error : 

You wrote `<gantt-tooltips ...><gantt-tooltips/>` instead of `<gantt-tooltips ...></gantt-tooltips>` :)

Actually the error comes from the documentation [here](https://www.angular-gantt.com/plugins/tooltips/) and it also exists for the progress plugin [here](https://www.angular-gantt.com/plugins/progress/).

You should probably update the documentation to avoid similar issues.

**Comment by Schweigi** [comment]
@v4l3r10 Thx for the tip. I changed the documentation.

**Comment by v4l3r10** [comment]
Thx to @TinOo512  for his eagle eyes !
Now all work fine ;)
