### ISSUE TITLE
Tasks rendering - general performance question.

### ISSUE THREAD

**Issue by ronihcohen** [angular-gantt/angular-gantt#418]
1. I have noticed that when I'm scrolling the gantt (left or right) all the tasks in the columns are re-rendering, when there is many tasks in the column there is a lag. What are the benefits of this behavior?
It will be more simple to render all task in given time frame only on load or when the time frame changes.

2. Angular isn't very good at DOM rendering, maybe we should use React instead?

**Comment by zhendong590** [comment]
maybe wait for angularJS 2.0

**Comment by Schweigi** [comment]
Hmm, what exactly do you mean by re-rendered?

We use the `track by` feature of Angular so the current visible tasks should only be added to the DOM, when they enter the visible area. They get removed from the DOM once the tasks leaves the visible area. If we wouldn't do that then the Gantt would be really slow.

**Comment by ronihcohen** [comment]
But why it will be really slow? Once all tasks are in the DOM the gantt
should work faster, only the first loading will take more time and we can
limit the time frame so it won't take forever.

**Comment by Toilal** [comment]
I'm sorry, but it's false. Column limit filter, the thing that automatically removes invisible elements from DOM, has been implemented for performance reason. 

Having all the columns in the DOM would make the thing really slower, as stated by @Schweigi. When DOM is to heavy, it really get slower because the browser needs to handle them even if they are not rendered.

You can try to change implementation of [columnLimit.filter.js](https://github.com/angular-gantt/angular-gantt/blob/master/src/core/ui/limit/columnLimit.filter.js) to always return input columns, and you will see it gets really slower in gantt with a minimal column count.
