### ISSUE TITLE
looping issue

### ISSUE THREAD

**Issue by simkeyur** [angular-gantt/angular-gantt#448]
I am trying to loop tasks like this:

```javascript

angular.module('angularGanttDemoApp')
.service('Sample', function Sample() {
    return {
        getSampleData: function() {
        	
            return [
				for(i=0; i<6; i++){
                    {name: ganttArray[i][0], movable: {allowResizing: false}, tasks: [
						{name: ganttArray[i][0], 
							color: '#9FC5F8', 
							from: new Date(ganttArray[i][1], ganttArray[i][2], ganttArray[i][3], ganttArray[i][4], ganttArray[i][5], ganttArray[i][6]), 
							to: new Date(ganttArray[i+1][1], ganttArray[i+1][2], ganttArray[i+1][3], ganttArray[i+1][4], ganttArray[i+1][5], ganttArray[i+1][6]),
                            progress: {percent: 100, color: '#3C8CF8'}, 
                            movable: false},
                    ]},
				}
                ];
				
        }
    };
})
```

but its giving me bunch of errors. Any better way to approach this?

**Comment by DanTalash** [comment]
While it is unclear exactly what you're attempting to do, it seems like you want to generate some row / task data through a loop. However, your syntax is incorrect. 

* If you want to add rows through a loop, then you need to:
  * Declare an array to store the data while it is being constructed
  * Add an entry to the array on each loop iteration
  * Return the resulting array.

* You appear to be trying to take data from a different array called `ganttArray`. 
  * This array is nowhere to be found in your code snippet. 
  * Are you declaring it globally in a different section of your code?


You probably want something more similar to:

```javascript
            getSampleData: function() {
				var result = []; //Declare an array

				for (var i = 0; i < 6; i++) {
					//Add an entry to the array for each loop iteration.
					result.push({
						name : 'Row ' + (i + 1),
						movable : false,
						tasks : [{
							name : 'Task ' + (i + 1),
							color : '#9FC5F8',
							from : new Date(),
							to : new Date(),
							progress : {
								percent : 100,
								color : '#3C8CF8'
							},
							movable : false
						}, ]
					});
				}

				return result; //Return resulting array
            },
```

The above code will create 7 rows, each containing one task.

You will also need to remove (or modify) the `api.data.on.change` event from the sample code, as this event is tied to the default sample data, and will otherwise cause a crash.

**Comment by Toilal** [comment]
Thanks for your reply @DanTalash, seems to be a basic JavaScript syntax error of course :)
