### ISSUE TITLE
CommonJS support

### ISSUE THREAD

**Issue by Schweigi** [angular-gantt/angular-gantt#549]
It would be great to have CommonJS support. Angular has it and it makes the use of dependencies much easier. See: http://angularjs.blogspot.com/2015/02/new-angularjs-releases-140-beta5-and.html

Possible usage example:

```
var angular = require('angular');
angular.module('myApp', [
  require('angular'),
  require('angular-gantt'),
  require('angular-gantt-table-plugin')
]);
```

**Comment by Schweigi** [comment]
I would need help for this. It's very easy to make a module for a single NPM package and use it with Browserify but for our plugins it would be necessary to expose multiple modules in a single package. Somehow I didn't see how to do this yet.

**Comment by Toilal** [comment]
I'm in favor of switching to a better module management, and more globally a new build system.

To go forward and prepare angular 2 migration #350, we could switch directly to [SystemJS](https://github.com/systemjs/systemjs) and ES6 in the project. SystemJS is the ES6 module loader used in angular 2. SystemJS can load any ES5 modules packages (AMD, CommonJS, ...), so we should then rely on npm packages for dependency instead of bower.

It requires some build script to provide ES5 CommonJS modules to users of angular-gantt, but it seems doable with [babel](https://babeljs.io/).

**Comment by Toilal** [comment]
Some links on subject:

- http://ilikekillnerds.com/2015/07/jspm-vs-webpack/ (That's why I'm not in favor of webpack, let's jump an historical step instead ...)
- http://martinmicunda.com/2015/02/09/how-to-start-writing-apps-with-es6-angular-1x-and-jspm/

**Comment by Toilal** [comment]
One advantage for webpack though : It supports things outside of pure javascript scope, like stylesheets and precompilation. But it seems not possible to use both Webpack and SystemJS.

**Comment by Schweigi** [comment]
I'm definitely in favor of System.js. It removes the development build step and is future proof. It also allows export of CommonJS, AMD and other module formats to keep compatibility with current module systems.

**Comment by Toilal** [comment]
@Schweigi Maybe it's time to start migrating to angular 2 as it's in beta now ... I'll start reading this about ngUpgrade and ngForward to engage angular-gantt in this process ... But don't expect anything before February I think :p.

**Comment by Toilal** [comment]
Closing in favor of #732. 

Fun to see how things change quickly in JS world, System.js was the hype 2 years ago, but now it seems to just suck and has lost versus Webpack. For now ...
