### ISSUE TITLE
GanttColumnGenerator

### ISSUE THREAD

**Issue by tamybilly** [angular-gantt/angular-gantt#554]
This method is generating the expanded columns at a wrong leftoffset. The first column that goes on the previousColumns property gets a left=0 (with a columnWidth of 100) when it is supposed to get -100. Because of this if there is a bar that starts exactly where the chart starts it will get the wrong position, instead of having a left=0, it gets a left=100.

**Comment by tamybilly** [comment]
I actually have the solution for this. How can i contribute by submitting the change?

**Comment by Toilal** [comment]
The issue you are describing was fixed in this commit https://github.com/angular-gantt/angular-gantt/commit/0a7f37220b56856938fd9d92eba6348ce5ce10aa, included in v1.2.8 release.

Please use latest version. I'll also close your "fix", I'm not sure what it really does and what it really fix.

If you can reproduce this issue with latest release, please open another issue.
