### ISSUE TITLE
Lock Side table Width

### ISSUE THREAD

**Issue by paips** [angular-gantt/angular-gantt#624]
Hi all,

I try to lock mys side with on angular gantt but i can't.
Currently side width auto adjust to content length. I would like to lock the width to a certain value, even if the content is larger.

I tried adding side-width='100px' but i have a strange result.

Can anyone help me?
Thanks a lot

**Comment by Toilal** [comment]
You have to put additional quotes if 100px is defined directly in template.

Hi all,

I try to lock mys side with on angular gantt but i can't.
Currently side width auto adjust to content length. I would like to lock
the width to a certain value, even if the content is larger.

I tried adding side-width='100px' but i have a strange result.

Can anyone help me?
Thanks a lot

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/angular-gantt/angular-gantt/issues/624>

**Comment by paips** [comment]
Hi Toilal,

Thanks a lot for your answer.

I finally used api.side.setWidth(100), and it seems fine.

Thanks again
Best regards
