### ISSUE TITLE
Angular 2?

### ISSUE THREAD

**Issue by shyamal890** [angular-gantt/angular-gantt#765]
This plugin is awesome. With Angular 2 all the performance issues can be addressed, is there any plans for the same?

**Comment by mklinke** [comment]
@shyamal890 You will find kind of an answer  in #350.
My team mates and I were even briefly looking into using [ngUpgrade](https://angular.io/guide/upgrade) to keep using the AngularJS-version until there is a replacement for Angular. Sadly, we didn't get it working yet. We'll probably have to buy a component, since the repository https://github.com/angular-gantt/gantt is still empty and there hasn't been activity for months.

**Comment by Toilal** [comment]
This repository doesn't support Angular and I don't have time nor need for now to port it on Angular. 

@mklinke is on the right way, but there's much refactoring work on the project to make it work, and there's some hacky things in angular-gantt source code that would make this path hard to achieve if possible...
